services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: resume
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - ./fastapi-application/.env.template